version: '2'
services:

  db:
    container_name: db
    image: arm64v8/mariadb
    restart: always
    command: --sql_mode=""
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
     - mysql-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 80:80
    volumes:
      - phpmyadmin:/var/lib/phpmyadmin

volumes:
  mysql-volume:
  phpmyadmin:
